name: Deploy to Fastly

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Build Vite site
        run: npm run build

      - name: Install compute-js dependencies
        working-directory: ./compute-js
        run: npm install

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@v5

      - name: Deploy to Fastly
        working-directory: ./compute-js
        run: fastly compute publish --non-interactive
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
