name: Deploy to Fastly

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Setup Fastly CLI
        run: |
          curl -sS https://downloads.fastly.com/cli/fastly_install.sh | bash
          echo "$HOME/.fastly/bin" >> $GITHUB_PATH

      - name: Deploy to Fastly
        run: |
          cd compute-js
          npm install
          fastly compute publish --non-interactive
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
